spring.application.name=order-service

server.port=8082

#oracle config
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=ORDER_DB_M

#which db and how should write sql for it
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl.auto=create
spring.jpa.generate-ddl-=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

#eureka config 
#giving eureka server details

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#register

eureka.client.register-with-eureka=true
#get all service register
eureka.client.fetch-registry=true
#instead oh use ipaddress
eureka.instance.prefer-ip-address=true
